[package]
name = "cryptopals"
version = "0.1.0"
authors = ["eklavya"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"
itertools = "0.10.0"
openssl = "0.10"
rustls = "0.19.0"